# **Работа с API**

Шаг 1: Получение информации обо всех книгах

In [1]:
import requests
import pandas as pd

In [6]:
# Базовый URL API
api_base_url = 'https://www.anapioficeandfire.com/api/'

In [27]:
book_response = requests.get(api_base_url + 'books').json()

print("Количество книг:", len(book_response))

print("Первые три книги:\n", book_response[:3])  # показываем первые три книги

df_books = pd.DataFrame(book_response)
print("\nDataFrame с книгами:\n")
df_books.head()

Количество книг: 10
Первые три книги:

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

Шаг 2: Получение информации обо всех домах Вестероса

In [22]:
house_response = requests.get(api_base_url + 'houses').json()
print("\nПервые три дома:\n", house_response[:3])  # показываем первые три дома

df_houses = pd.DataFrame(house_response)
print("\nDataFrame со всеми домами:\n")
df_houses.head()

Первые три дома:
 [{'url': 'https://www.anapioficeandfire.com/api/houses/1', 'name': 'House Algood', 'region': 'The Westerlands', 'coatOfArms': 'A golden wreath, on a blue field with a gold border(Azure, a garland of laurel within a bordure or)', 'words': '', 'titles': [], 'seats': [], 'currentLord': '', 'heir': '', 'overlord': 'https://www.anapioficeandfire.com/api/houses/229', 'founded': '', 'founder': '', 'diedOut': '', 'ancestralWeapons': [], 'cadetBranches': [], 'swornMembers': []}, {'url': 'https://www.anapioficeandfire.com/api/houses/2', 'name': 'House Allyrion of Godsgrace', 'region': 'Dorne', 'coatOfArms': 'Gyronny Gules and Sable, a hand couped Or', 'words': 'No Foe May Pass', 'titles': [], 'seats': ['Godsgrace'], 'currentLord': 'https://www.anapioficeandfire.com/api/characters/298', 'heir': 'https://www.anapioficeandfire.com/api/characters/1922', 'overlord': 'https://www.anapioficeandfire.com/api/houses/285', 'founded': '', 'founder': '', 'diedOut': '', 'ancestralWeapons': [], 'cadetBranches': [], 'swornMembers': ['https://www.anapioficeandfire.com/api/characters/298', 'https://www.anapioficeandfire.com/api/characters/1129', 'https://www.anapioficeandfire.com/api/characters/1301', 'https://www.anapioficeandfire.com/api/characters/1922']}, {'url': 'https://www.anapioficeandfire.com/api/houses/3', 'name': 'House Amber', 'region': 'The North', 'coatOfArms': '', 'words': '', 'titles': [], 'seats': [], 'currentLord': '', 'heir': '', 'overlord': '', 'founded': '', 'founder': '', 'diedOut': '', 'ancestralWeapons': [], 'cadetBranches': [], 'swornMembers': []}]

DataFrame со всеми домами:

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]

Шаг 3: Получение информации о домах с девизом

In [30]:
homes_with_titles_response = requests.get(api_base_url + 'houses/?hasTitles=true').json()
print("\nПервые три дома с девизами:\n", homes_with_titles_response[:3])  # показываем первые три дома с девизами

df_houses_with_titles = pd.DataFrame(homes_with_titles_response)
print("\nDataFrame с домами, имеющими девиз:\n")
df_houses_with_titles.head()

Первые три дома с девизами:
 [{'url': 'https://www.anapioficeandfire.com/api/houses/7', 'name': 'House Arryn of the Eyrie', 'region': 'The Vale', 'coatOfArms': 'A sky-blue falcon soaring against a white moon, on a sky-blue field(Bleu celeste, upon a plate a falcon volant of the field)', 'words': 'As High as Honor', 'titles': ['King of Mountain and Vale (formerly)', 'Lord of the Eyrie', 'Defender of the Vale', 'Warden of the East'], 'seats': ['The Eyrie (summer)', 'Gates of the Moon (winter)'], 'currentLord': 'https://www.anapioficeandfire.com/api/characters/894', 'heir': 'https://www.anapioficeandfire.com/api/characters/477', 'overlord': 'https://www.anapioficeandfire.com/api/houses/16', 'founded': 'Coming of the Andals', 'founder': 'https://www.anapioficeandfire.com/api/characters/144', 'diedOut': '', 'ancestralWeapons': [], 'cadetBranches': ['https://www.anapioficeandfire.com/api/houses/6'], 'swornMembers': ['https://www.anapioficeandfire.com/api/characters/49', 'https://www.anapioficeandfire.com/api/characters/92', 'https://www.anapioficeandfire.com/api/characters/93', 'https://www.anapioficeandfire.com/api/characters/107', 'https://www.anapioficeandfire.com/api/characters/223', 'https://www.anapioficeandfire.com/api/characters/265', 'https://www.anapioficeandfire.com/api/characters/300', 'https://www.anapioficeandfire.com/api/characters/356', 'https://www.anapioficeandfire.com/api/characters/477', 'https://www.anapioficeandfire.com/api/characters/508', 'https://www.anapioficeandfire.com/api/characters/540', 'https://www.anapioficeandfire.com/api/characters/548', 'https://www.anapioficeandfire.com/api/characters/558', 'https://www.anapioficeandfire.com/api/characters/572', 'https://www.anapioficeandfire.com/api/characters/688', 'https://www.anapioficeandfire.com/api/characters/894', 'https://www.anapioficeandfire.com/api/characters/1068', 'https://www.anapioficeandfire.com/api/characters/1193', 'https://www.anapioficeandfire.com/api/characters/1280', 'https://www.anapioficeandfire.com/api/characters/1443', 'https://www.anapioficeandfire.com/api/characters/1655', 'https://www.anapioficeandfire.com/api/characters/1693', 'https://www.anapioficeandfire.com/api/characters/1715', 'https://www.anapioficeandfire.com/api/characters/1884']}, {'url': 'https://www.anapioficeandfire.com/api/houses/8', 'name': 'House Ashford of Ashford', 'region': 'The Reach', 'coatOfArms': 'Tenny, a sun in splendour beneath a chevron inverted argent', 'words': 'Our Sun Shines Bright', 'titles': ['Lord of Ashford'], 'seats': ['Ashford'], 'currentLord': '', 'heir': '', 'overlord': 'https://www.anapioficeandfire.com/api/houses/398', 'founded': '', 'founder': '', 'diedOut': '', 'ancestralWeapons': [], 'cadetBranches': [], 'swornMembers': ['https://www.anapioficeandfire.com/api/characters/121', 'https://www.anapioficeandfire.com/api/characters/641', 'https://www.anapioficeandfire.com/api/characters/895', 'https://www.anapioficeandfire.com/api/characters/1812']}, {'url': 'https://www.anapioficeandfire.com/api/houses/10', 'name': 'House Baelish of Harrenhal', 'region': 'The Riverlands', 'coatOfArms': 'A field of silver mockingbirds, on a green field(Vert, semé of mockingbirds argent)', 'words': '', 'titles': ['Lord Paramount of the Trident', 'Lord of Harrenhal'], 'seats': ['Harrenhal'], 'currentLord': 'https://www.anapioficeandfire.com/api/characters/823', 'heir': '', 'overlord': 'https://www.anapioficeandfire.com/api/houses/16', 'founded': '299 AC', 'founder': 'https://www.anapioficeandfire.com/api/characters/823', 'diedOut': '', 'ancestralWeapons': [], 'cadetBranches': [], 'swornMembers': ['https://www.anapioficeandfire.com/api/characters/651', 'https://www.anapioficeandfire.com/api/characters/804', 'https://www.anapioficeandfire.com/api/characters/823', 'https://www.anapioficeandfire.com/api/characters/957', 'https://www.anapioficeandfire.com/api/characters/970']}]

DataFrame с домами, имеющими девиз:

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/16,299 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/15,,,,[],[],[https://www.anapioficeandfire.com/api/charact...

# **Работа с БД**

Шаг 1: Подключение к базе данных

In [31]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 77.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10

In [33]:
import psycopg2

In [34]:
# Попытка установить соединение с базой данных
try:
    conn = psycopg2.connect(
    host="hh-pgsql-public.ebi.ac.uk",
    database="pfmegrnargs",
    user="reader",
    password="NWDMCE5xdipIjRrp"
)
    print("Connection established successfully.")
except:
    print("Can't establish connection to database.")

Connection established successfully.

Шаг 2: Извлечение первых 10 записей из таблицы rnc_database

In [35]:
# Получение 10 строк из таблицы rnc_database
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnc_database LIMIT 10')  # Используем LIMIT 10 для ограничения числа строк
    result = cursor.fetchall()

In [36]:
# Преобразование в Pandas DataFrame
df_full = pd.DataFrame(result, columns=[col.name for col in cursor.description])
print("Полный DataFrame с первыми 10-ю строками:")
print(df_full)

Полный DataFrame с первыми 10-ю строками:
   id  timestamp userstamp      descr  current_release full_descr alive  \
0  21 2017-05-02    RNACEN    NONCODE              146    NONCODE     Y
1   5 2017-05-17    RNACEN       VEGA               98       VEGA     N
2  26 2017-05-01    RNACEN    GENCODE              450    GENCODE     N
3   1 2017-05-01    RNACEN        ENA              968        ENA     Y
4  14 2017-05-01    RNACEN       TAIR              982       TAIR     Y
5   9 2017-05-01    RNACEN     REFSEQ              969     RefSeq     Y
6  41 2017-05-01    RNACEN  GENECARDS              978  MalaCards     Y
7  10 2017-05-01    RNACEN        RDP               85        RDP     Y
8  20 2017-05-01    RNACEN  LNCIPEDIA              935  LNCipedia     Y
9  15 2017-05-02    RNACEN   WORMBASE              970   WormBase     Y

  for_release display_name  project_id  avg_length  min_length  max_length  \
0                  NONCODE                  1130.0       201.0    244296.0
1                     VEGA   PRJEB4568         NaN         NaN         NaN
2                  GENCODE                   889.0        32.0    205012.0
3                      ENA                   412.0        10.0    900074.0
4                     TAIR    PRJ_TAIR       384.0        19.0      6227.0
5                   RefSeq                   703.0        15.0     91667.0
6                GeneCards                  1292.0        16.0    347561.0
7                      RDP                  1536.0      1337.0      1600.0
8                LNCipedia                  1534.0       200.0    152544.0
9                 WormBase  PRJNA13758       171.0        17.0     84141.0

   num_sequences  num_organisms  \
0         234669              7
1              0              0
2          47677              2
3       12086180         814855
4           4406              1
5         120355          22524
6         425357              1
7           4779           2487
8         126876              1
9          25550              1

                                         description  \
0  is an integrated knowledge database dedicated ...
1  is a repository for high-quality gene models p...
2  produces high quality reference gene annotatio...
3  provides a comprehensive record of the world's...
4  is a database of genetic and molecular biology...
5  is a comprehensive, integrated, non-redundant,...
6  is a searchable, integrative database that pro...
7  provides quality-controlled, aligned and annot...
8  is a comprehensive compendium of human long no...
9  curates, stores and displays genomic and genet...

                                   url  \
0              http://www.noncode.org/
1            http://vega.sanger.ac.uk/
2             http://gencodegenes.org/
3   https://www.ebi.ac.uk/ena/browser/
4          http://www.arabidopsis.org/
5  http://www.ncbi.nlm.nih.gov/refseq/
6           https://www.genecards.org/
7              http://rdp.cme.msu.edu/
8            http://www.lncipedia.org/
9             http://www.wormbase.org/

                                             example  \
0  [{'upi': 'URS000019B796', 'taxid': 9606}, {'up...
1  [{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...
2  [{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...
3  [{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...
4  [{'upi': 'URS0000591E4F', 'taxid': 3702}, {'up...
5  [{'upi': 'URS000075A3E5', 'taxid': 10090}, {'u...
6  [{'upi': 'URS0000EBFCE3', 'taxid': 9606}, {'up...
7  [{'upi': 'URS0000434740', 'taxid': 338963}, {'...
8  [{'upi': 'URS000081175C', 'taxid': 9606}, {'up...
9  [{'upi': 'URS000022A09E', 'taxid': 6239}, {'up...

                                           reference
0  [{'title': 'NONCODE 2016: an informative and v...
1  [{'title': 'The GENCODE v7 catalog of human lo...
2  [{'title': 'GENCODE: the reference human genom...
3  [{'title': 'The European Nucleotide Archive in...
4  [{'title': 'The Arabidopsis Information Resour...
5  [{'title': 'RefSeq: an update on mammalian ref...
6  [{'title': 'The GeneCards Suite: From Gene Dat...
7  [{'title': 'Ribosomal Database Project: data a...
8  [{'title': 'An update on LNCipedia: a database...
9  [{'title': 'WormBase 2012: more genomes, more ...

Шаг 3: Сохраняем выбранные колонки

In [37]:
# Выборка необходимых столбцов
with conn.cursor() as cursor:
    cursor.execute('''
        SELECT display_name, num_sequences, num_organisms, url
        FROM rnc_database
        LIMIT 10
    ''')
    selected_result = cursor.fetchall()

In [38]:
# Преобразование выбранного подмножества в новый DataFrame
df_selected = pd.DataFrame(selected_result, columns=["display_name", "num_sequences", "num_organisms", "url"])
print("\nDataFrame с необходимыми столбцами (display_name, num_sequences, num_organisms, url):")
print(df_selected)

DataFrame с необходимыми столбцами (display_name, num_sequences, num_organisms, url):
  display_name  num_sequences  num_organisms  \
0      NONCODE         234669              7
1         VEGA              0              0
2      GENCODE          47677              2
3          ENA       12086180         814855
4         TAIR           4406              1
5       RefSeq         120355          22524
6    GeneCards         425357              1
7          RDP           4779           2487
8    LNCipedia         126876              1
9     WormBase          25550              1

                                   url
0              http://www.noncode.org/
1            http://vega.sanger.ac.uk/
2             http://gencodegenes.org/
3   https://www.ebi.ac.uk/ena/browser/
4          http://www.arabidopsis.org/
5  http://www.ncbi.nlm.nih.gov/refseq/
6           https://www.genecards.org/
7              http://rdp.cme.msu.edu/
8            http://www.lncipedia.org/
9             http://www.wormbase.org/

In [39]:
# Завершаем работу с базой данных
conn.close()